# Generated by Django 5.1.6 on 2025-04-25 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_dj_app', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsreg',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
